### ISSUE TITLE
Buttons programming

### ISSUE THREAD

**Issue by gamelaster** [nodep/NovaBox#1]
Hello,

Very nice project, I really like it. I made my own CSR8635 headset, but I have problems with buttons, I just can't set it via CSR8600 Headset Config tool. Do you have any ideas where could be a problem?

Thank you

**Comment by gamelaster** [comment]
Okay, nevermind, I figured out somehow 😆

**Comment by gamelaster** [comment]
Also, if you know how to make the charging working, please let me know 😀

**Comment by nodep** [comment]
Sorry, I have never tried to get the charger working. I have no need for it.
